CREATE USER ATGCORE IDENTIFIED BY ATGCORE DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT EXPORT FULL DATABASE TO ATGCORE;
GRANT IMPORT FULL DATABASE TO ATGCORE;
GRANT UNLIMITED TABLESPACE TO ATGCORE;
GRANT "CONNECT" TO ATGCORE;
GRANT "EXP_FULL_DATABASE" TO ATGCORE;
GRANT "IMP_FULL_DATABASE" TO ATGCORE;

CREATE USER ATGCATALOGA IDENTIFIED BY ATGCATALOGA DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT EXPORT FULL DATABASE TO ATGCATALOGA;
GRANT IMPORT FULL DATABASE TO ATGCATALOGA;
GRANT UNLIMITED TABLESPACE TO ATGCATALOGA;
GRANT "CONNECT" TO ATGCATALOGA;
GRANT "EXP_FULL_DATABASE" TO ATGCATALOGA;
GRANT "IMP_FULL_DATABASE" TO ATGCATALOGA;

CREATE USER ATGCATALOGB IDENTIFIED BY ATGCATALOGB DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT EXPORT FULL DATABASE TO ATGCATALOGB;
GRANT IMPORT FULL DATABASE TO ATGCATALOGB;
GRANT UNLIMITED TABLESPACE TO ATGCATALOGB;
GRANT "CONNECT" TO ATGCATALOGB;
GRANT "EXP_FULL_DATABASE" TO ATGCATALOGB;
GRANT "IMP_FULL_DATABASE" TO ATGCATALOGB;


CREATE USER ATGPUBCORE IDENTIFIED BY ATGPUBCORE DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT EXPORT FULL DATABASE TO ATGPUBCORE;
GRANT IMPORT FULL DATABASE TO ATGPUBCORE;
GRANT UNLIMITED TABLESPACE TO ATGPUBCORE;
GRANT "CONNECT" TO ATGPUBCORE;
GRANT "EXP_FULL_DATABASE" TO ATGPUBCORE;
GRANT "IMP_FULL_DATABASE" TO ATGPUBCORE;

EXIT
